### ISSUE TITLE
using tiny-process-library apparently means heavy external dependencies on Windows

### ISSUE THREAD

**Issue by divanchykhin** [O-Log-N/Hare-IDL#54]
in particular, installation of third-party MSYS2. Please check. If so, alternative ways of managing processes is better to consider (if/as system-dependent code is limited, it can be localized and written separately for target platforms providing a uniform interface for upper levels)

**Comment by marcosbracco** [comment]
I don't think it does. Has some optional code when MSYS2 is present but not a dependency.
However, it was just the first tool I found that meet all my needs, If we need to write it on our own, is not an issue.
Other little detail we may want to change in future is using temporary file instead of stdout, since reading stdout requires lauching separate threads for that. Using a temporary file for exchange does not require extra threads. I will need to verify we still be getting errors messages piped to our error stream.

**Comment by nobugs-hare** [comment]
The whole question here is about "Whether user needs to install something additional?" If yes - we do need to replace it (asking user to install 3rd-party tool just so we can launch processes is Way Too Much), if no - I don't care. Can somebody check that it works on a "clean" Windows machine (without MSYS2 installed)?

**Comment by marcosbracco** [comment]
Ok, I'll check

**Comment by marcosbracco** [comment]
Ok, there are not extra dependencies.
Tried on fresh Windows Server 2013 from AWS, with only installing Visual C 2015 redistributable for runtime libraries, dropped the both .exe (C++2HareIDL.exe and the idl frontend using tiny-process-library), both compiled on my development Windows on 'release' mode (Microsoft does not redistribute debug runtime libraries).
It worked normally.
C++ headers where not found because they where not there, so only primitive C++ types work.
